# Site settings
title: cratacenter
email: cratacenter@wcyd.org
description: > # this means to ignore newlines until "baseurl:"
  Building a datacenter in a crate.
baseurl: "/cratacenter" # the subpath of your site, e.g. /blog
url: "https://jameswhite.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: websages

# Build settings
markdown: kramdown

exclude: ["Gemfile", "deploy.sh", "README.md", "Gemfile.lock", ".gitignore", "screenshots"]

# See http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/index.html
