#!/bin/sh
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd "$DIR"
export PATH=/usr/share/rbenv/shims:$PATH
export RBENV_VERSION="$(cat .ruby-version)"

if [ "$(uname -s)" = "Darwin" ]; then
  brew update >/dev/null
  brew bundle check &>/dev/null || brew bundle
  brew bootstrap-rbenv-ruby
fi

echo "==> Installing gem dependencies…"
gems_path=vendor/gems
rm -rf "${DIR}/.bundle"
bundle config set path "${gems_path}"
bundle check 2>&1 > /dev/null || {
  bundle binstubs
  bundle clean
}
